idf_component_register(
    SRCS
        "main.cpp"
        "ha_config.cpp"
        "ha_entities.cpp"
        "ha_service.cpp"
        "battery_monitor.cpp"
        "board_display.cpp"
        "panel_ui.cpp"
        "web_config.cpp"
        "camera_wake.cpp"
        "features_config.cpp"
        "fonts/lv_font_polish_18.c"
        "fonts/lv_font_polish_20.c"
        "fonts/lv_font_polish_22.c"
        "fonts/lv_font_polish_24.c"
        "fonts/lv_font_icons_18.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        "nvs_flash"
        "spiffs"
        "esp_event"
        "esp_netif"
        "esp_wifi"
        "esp_adc"
        "json"
        "esp-tls"
        "esp_http_server"
        "esp_http_client"
        "esp_websocket_client"
        "esp_lcd_touch"
        "esp-wifi-connect"
        "lvgl"
        "esp_lvgl_port"
        "esp_wifi_remote"
        "esp32_p4_function_ev_board"
        "esp_hosted"
        "esp_video"
        "esp_cam_sensor"
        "human_face_detect"
)